import type { Metadata } from "next";
import localFont from "next/font/local";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import  Banner  from "./banner";

const emeraldFont = localFont({
  src: '../../public/fonts/pokemon-emerald.ttf',
})


export const metadata: Metadata = {
  title: "Battle Factory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={emeraldFont.className}>
        <Banner />
        {children}
        </body>
    </html>
  );
}
